### ISSUE TITLE
mac版本是不是不支持插件功能？

### ISSUE THREAD

**Issue by hunter-tp** [plylrnsdy/wiz-editor-jsmind#12]
如题

**Comment by plylrnsdy** [comment]
据我所知，mac 版的为知笔记不支持插件功能：
在 https://www.wiz.cn/zh-cn/download.html 中的插件也写作“Windows 插件”

**Comment by hunter-tp** [comment]
> 据我所知，mac 版的为知笔记不支持插件功能：
> 在 https://www.wiz.cn/zh-cn/download.html 中的插件也写作“Windows 插件”

好吧，多谢
